### ISSUE TITLE
lcd_vsync is used but has no driver.

### ISSUE THREAD

**Issue by derekmulcahy** [daveshah1/IcySprites#2]
When running make I get the message
```
Warning: Wire top.\lcd_vsync is used but has no driver.
```
It looks like you intended to get lcd_vsync from the lcd_ctrl instance but you passed lcd_hsync twice.
```
                  .lcd_hsync(lcd_hsync),
                  .lcd_hsync(lcd_hsync),
```

**Comment by daveshah1** [comment]
Oops! Thanks for catching this. As far as I can see the LCD I was using doesn't actually look at VSYNC or HSYNC, only DEN. I'll sort this out though. It may explain some odd behaviour I've seen.
